# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68bde0df53fabf5e25f408a7059dabf196dcd2553e1e338880fb511796a6bbb0bc3770f9a286ec47a74842357b801c4805d881e3c1fa0d219b154e3bd4c84f06

test:
  secret_key_base: d7434c7b6775f83af1b927ead401348e60f35f633c6651894720490ec0bcddc7ddcb795911bf5d8e3d2ea5acfed259852bb2d180f10db32fb044ff0bff21b7ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
